version: '3'
services:
  app:
    container_name: UTubeScrappy
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
